spring:
  application:
    name: rasp
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##YD
    password: YD
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
   hibernate:
      ddl-auto: create
   show-sql: true
   
server:
  port: 8081